# Generated by Django 3.1.7 on 2021-03-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210302_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published', '-updated', '-timestamp']},
        ),
    ]
